### ISSUE TITLE
Environment variables do not bootstrap correctly in the SSO tile

### ISSUE THREAD

**Issue by jjstreet** [pivotal-cf/identity-sample-apps#10]
I'm trying to follow the sample app for client_credential grant_type. I cannot figure out which environment variable corresponds with the scopes listed for the application within the SSO tile's management screen.

For example, if I have a scope of _foo.app.writer_ and I want to bootstrap my app with the manifest and use this scope, I was expecting to have something like:

`SSO_AUTHORITIES: uaa.resource, foo.app.writer`

The only scope that shows up is _uaa.resource_

**Comment by tnwang** [comment]
You are correct to use "SSO_AUTHORITIES" for the client credentials grant type. However, there are additional restrictions on "SSO_AUTHORITIES" for as compared to  "SSO_SCOPES". The resources must be pre-created (or created via "SSO_RESOURCES" in the same app manifest) and must also reside in the same space to be assigned as authorities, and these restrictions do not apply to scopes. This is for security purposes because client credential application authorities are directly usable with client ID/secret, whereas scopes require a user to also be assigned the same scope. 

You should be able to pre-create the resource (foo.app.writer) in the same space first or define it to be created as part of the same app manifest, and the bootstrap should work.

If you already created the scope in another space, you'll need to add the scope to your client manually as an administrator (this is in order to protect just anyone from being able to directly obtain your scope if they are using the same service plan).

**Comment by jjstreet** [comment]
I believe I've confirmed that the resources I am trying to use are already created in my space (they are visible in the resources tab of the SSO management app). The same result still occurs--I cannot apply these scopes to my app through the manifest bootstrapping environment variables. When viewing resources in the SSO management app, is the space where the scope originated shown somewhere specifically or can I assume they were created in the space?

I also cannot change other properties like `SSO_ACCESS_TOKEN_LIFETIME`

I tried to create a resource through `SSO_RESOURCES` and that resource isn't created either.

When creating a plan for the SSO tile, is it possible to restrict this auto-binding behavior I am trying to use? It is the only other explanation I can think of...

**Comment by tnwang** [comment]
Are you unbinding the old service binding after making the changes and rebinding with a new service instance? The app manifest bootstrap only works on the initial creation of the binding, so further updates actually require removal of the previous binding to work.

**Comment by jjstreet** [comment]
I unbound the app from the SSO tile, then deleted the app from the SSO tile management app. Then I deleted the app from the cloud. I then `cf push` my app back to the cloud.

Looking at the SSO tile app again, I see my app has bound to the service and is listed there. The grant type is correct and set to what the environment vars has (`client_credentials`). However there is only 1 authority specified: `uaa.resource` The pre-created resource that I specified in the manifest is not in the list of scopes.

**Comment by tnwang** [comment]
Which version of the SSO tile are you using, and would you be able to provide the snippets of your app manifest for `SSO_AUTHORITIES`?

I re-tried the functionality on SSO versions 1.4.4 and 1.5.1 and noted the following:
1. On 1.4.4, the SSO_AUTHORITIES were added only if they were created prior to the push. If they were specified in the same app manifest to be created, there is a known bug where it isn't assigned and I had to unbind and rebind, but the SSO AUTHORITIES were created in the OAuth Client Configurations via binding on the second bind.
2. On 1.5.1, the SSO_AUTHORITIES were added to my client configurations immediately, as we had fixed the bug with resources created not being assigned even if part of the same app manifest.

I used the following app manifest:

```
---
applications:
 - name: authcode-sample
   memory: 1GB
   instances: 1
   path: build/libs/authcode.jar
   services:
   - test-service-instance
   env:
     SKIP_SSL_VALIDATION: "true"

     # Grant type to be set for the application's UAA client configurations. Only one grant type per application is supported by the SSO service.
     GRANT_TYPE: client_credentials

     # Identity provider(s) to be set for the application's client configurations
     SSO_IDENTITY_PROVIDERS: uaa

     # Client authorities for the application, only used for client credentials grant type
     SSO_AUTHORITIES: openid, uaa.resource, todo1.read, todo1.write

     # Lifetime in seconds of the application's access token
     SSO_ACCESS_TOKEN_LIFETIME: 300

     # Resource(s) that the application will use as scopes/authorities to be created if they do not already exist during bootstrapping
     SSO_RESOURCES: |
       todo1.read:  Read Objects
       todo1.write: Write Objects
```

**Comment by jjstreet** [comment]
Unbinding and rebinding the app doesn't add the `SSO_AUTHORITIES` ive listed in the manifest.

Unfortunately, there's no easy way I can figure out the version of the tile since this is a company owned cloud and there's no version information in any of the app views or CLI commands.

My manifest is pretty much laid out like your example. I will try to confirm version information and anything strange we did to our on prem cloud.

**Comment by tnwang** [comment]
Closing this issue. Please re-open if the issue is still seen. SSO Tile 1.4.1+ must be used for bootstrap feature.

**Comment by louisthomas** [comment]
I still have this issue with SSO tile 1.6.0. 

```
    env:
      # Grant type to be set for the application's client configurations - Only one grant type per application is supported by SSO
      GRANT_TYPE: client_credentials

      # Client authorities for the application, only used for client credentials grant type
      SSO_AUTHORITIES: openid, uaa.resource,todo.read
#
#      # Resource(s) that the application will use as scopes/authorities to be created if they do not already exist during bootstrapping
      SSO_RESOURCES: |
         todo.read:  read
```
It creates the client without authorities and resources.
